{
 "title": "cothority",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "omniledger: login matrix",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "target": "omniledger.login-matrix" }
   ]
  },
  {
   "title": "omniledger: login wordpress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "target": "omniledger.login-wordpress" }
   ]
  },
  {
   "title": "cothority: transfer a coin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "target": "cothority.transfer-coin" }
   ]
  },
  {
   "title": "cothority: call BEvm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "target": "cothority.call-bevm" }
   ]
  },
  {
   "title": "cothority: leader",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(cothority.get-leader.*, 2), '_', '.')"
    }
   ]
  }
 ]
}