{
 "title": "services",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "c4dt.org: loading time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "target": "c4dt-org.loading-time" }
   ]
  },
  {
   "title": "cothority: transfer a coin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "target": "cothority.transfer-coin" }
   ]
  },
  {
   "title": "cothority: call BEvm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "target": "cothority.call-bevm" }
   ]
  },
  {
   "title": "omniledger: login matrix",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "target": "omniledger.login matrix" }
   ]
  },
  {
   "title": "omniledger: login wordpress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "target": "omniledger.login-wordpress" }
   ]
  }
 ]
}