version: "3.5"

services:
  graphite:
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "2003:2003"
    networks:
      - stats
    volumes:
      - ./data/graphite:/opt/graphite/conf
      - graphite:/opt/graphite/storage
  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    networks:
      - stats
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      # TODO remove editor role
      GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
    volumes:
      - ./data/grafana/config:/etc/grafana/provisioning
      - ./data/grafana/dashboards-to-provision:/var/lib/grafana/dashboards

volumes:
  graphite:

networks:
  stats:
