{
 "title": "drand",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "drand.c4dt.org: connectivity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "target": "drand.check-connectivity" }
   ]
  },
  {
   "title": "drand.c4dt.org: memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "target": "drand.get-used-memory" }
   ]
  },
  {
   "title": "drand.c4dt.org: CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "drand.get-cpu-percentage" }
   ]
  },
  {
   "title": "drand.c4dt.org: TTY activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "drand.get-tty-activity" }
   ]
  }
 ]
}