{
 "title": "services",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "omniledger: login matrix",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "ping time" }
   ],
   "targets": [
    { "target": "omniledger.login-matrix" }
   ]
  },
  {
   "title": "omniledger: login wordpress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "ping time" }
   ],
   "targets": [
    { "target": "omniledger.login-wordpress" }
   ]
  },
  {
   "title": "local@c4dt.org",
   "type": "graph",
   "description": "Additional installation on c4dtsrv2 using local disks",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "ping time" }
   ],
   "targets": [
    { "target": "website.wordpress-local.loaded" }
   ]
  },
  {
   "title": "c4dt.org: loading time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "ping time" }
   ],
   "targets": [
    { "target": "website.wordpress.loaded" }
   ]
  },
  {
   "title": "www.c4dt.org: loading time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "ping time" }
   ],
   "targets": [
    { "target": "website.wordpress-www.loaded" }
   ]
  },
  {
   "title": "showcase.c4dt.org: loading time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "ping time" }
   ],
   "targets": [
    { "target": "website.showcase.loaded" }
   ]
  },
  {
   "title": "matrix.c4dt.org: loading time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "ping time" }
   ],
   "targets": [
    { "target": "website.matrix.loaded" }
   ]
  },
  {
   "title": "library.c4dt.org: loading time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "ping time" }
   ],
   "targets": [
    { "target": "website.library.loaded" }
   ]
  },
  {
   "title": "cryptpad.c4dt.org: loading time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s", "label": "ping time" }
   ],
   "targets": [
    { "target": "website.cryptpad.loaded" }
   ]
  },
  {
   "title": "cothority: transfer a coin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "s", "label": "confirmation time" }
   ],
   "targets": [
    { "target": "cothority.transfer-coin" }
   ]
  },
  {
   "title": "cothority: call BEvm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "s", "label": "read time" }
   ],
   "targets": [
    { "target": "cothority.call-bevm" }
   ]
  },
  {
   "title": "cothority: leader",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(cothority.get-leader.*, 2), '_', '.')"
    }
   ]
  }
 ]
}