name: deploy to stats.c4dt.org

env:
  DEPLOY_USER: stats
  DEPLOY_HOST: stats.c4dt.org

on:
  workflow_run:
    workflows: ["lint"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1.1.0
        with:
          ssh-host: ${{ env.DEPLOY_HOST }}
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: rsync repository
        run: >
          rsync --verbose --archive --delete --exclude-from=.gitignore --exclude=/.git
          "$GITHUB_WORKSPACE/" "${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}:"
      - name: reload systemd's daemon
        run: ssh "${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}" systemctl --user daemon-reload
      - name: stop all timers
        run: >
          ssh "${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}" "systemctl --user list-timers |
            awk '/^$/ {exit} NR > 1 {print \$(NF-1)}' |
            xargs systemctl --user stop"
      - name: start each timer
        run: >
          ls "$GITHUB_WORKSPACE/.config/systemd/user/timers.target.wants" |
          xargs ssh "${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}" systemctl --user start
